export class Sukien {
  // @ts-ignore
  id: number;
  // @ts-ignore
  event_name: string;
  // @ts-ignore
  organizer: string;
  // @ts-ignore
  time_of_event: Date;
  // @ts-ignore
  place: string;
  // @ts-ignore
  describe_of_event: string;
  // @ts-ignore
  img: string;
  // @ts-ignore
  plan_file: string;
  // @ts-ignore
  number_of_collaborators: number;
  // @ts-ignore
  riteria: string;
  // @ts-ignore
  end_day: Date;
  // @ts-ignore
  status_of_event: string;
  // @ts-ignore
  owner_event_id: number;
  // @ts-ignore
  hot: boolean;
}
